{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "advanced-sftp-exporter.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "advanced-sftp-exporter.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "advanced-sftp-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
