apiVersion: v1
kind: Service
metadata:
  name: {{ include "advanced-sftp-exporter.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "advanced-sftp-exporter.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "advanced-sftp-exporter.selectorLabels" . | nindent 4 }}
